[project]
name = "arch-ticket-hunter"
version = "0.1.0"
description = "Ticket hunter for Archstoyanie Festival"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "dotenv>=0.9.9",
    "flask>=3.1.0",
    "requests>=2.32.3",
]
