services:
  - type: worker
    name: ticket-checker
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: STATUS_INTERVAL_HOURS
        value: "3"